services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true   # necesario en Windows para que detecte cambios
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules        # evita que Windows pise el node_modules de Linux
    command: npm run dev

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: tienda
      POSTGRES_PASSWORD: tienda_pass
      POSTGRES_DB: tienda_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: