services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: tienda
      POSTGRES_PASSWORD: tienda_pass
      POSTGRES_DB: tienda_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
##Intento 1